import type { TarotCardMeta, TarotCardId } from "./types.js";

export const TAROT_CARDS: Record<TarotCardId, TarotCardMeta> = {
  "the-fool": {
    id: "the-fool",
    name: "The Fool",
    nameKo: "바보",
    arcana: "major",
    number: 0,
    keywords: ["new beginning", "spontaneity", "risk", "potential"],
    keywordsKo: ["새로운 시작", "즉흥성", "리스크", "가능성"],
    meaningUpright: "새로운 시작, 무한한 가능성, 리스크 감수",
    meaningReversed: "무모함, 준비 부족, 경솔한 결정",
    imageUrl: "/cards/the-fool.png",
    toneGuide: "가볍고 호기심 넘치는 에너지. 미지의 여정을 시작하는 느낌.",
    isActive: true,
  },
  "the-magician": {
    id: "the-magician",
    name: "The Magician",
    nameKo: "마법사",
    arcana: "major",
    number: 1,
    keywords: ["willpower", "skill", "manifestation", "resourcefulness"],
    keywordsKo: ["의지력", "기술", "현실화", "자원 활용"],
    meaningUpright: "의지력과 기술로 목표를 현실로 만드는 힘",
    meaningReversed: "재능 낭비, 조종, 부실한 계획",
    imageUrl: "/cards/the-magician.png",
    toneGuide: "집중되고 능동적인 에너지. 모든 도구를 갖추고 행동하는 느낌.",
    isActive: true,
  },
  "the-high-priestess": {
    id: "the-high-priestess",
    name: "The High Priestess",
    nameKo: "여교황",
    arcana: "major",
    number: 2,
    keywords: ["intuition", "mystery", "patience", "hidden knowledge"],
    keywordsKo: ["직관", "신비", "인내", "숨겨진 정보"],
    meaningUpright: "직관을 신뢰하라. 드러나지 않은 정보가 있다.",
    meaningReversed: "정보 은폐, 판단 흐림, 표면만 보는 실수",
    imageUrl: "/cards/the-high-priestess.png",
    toneGuide: "차분하고 신비로운 에너지. 관망과 직관의 시간.",
    isActive: true,
  },
  "the-empress": {
    id: "the-empress",
    name: "The Empress",
    nameKo: "여황제",
    arcana: "major",
    number: 3,
    keywords: ["abundance", "growth", "fertility", "nurturing"],
    keywordsKo: ["풍요", "성장", "생산성", "육성"],
    meaningUpright: "풍요로운 성장, 생산성 증가, 번영의 시기",
    meaningReversed: "성장 정체, 과잉, 의존성",
    imageUrl: "/cards/the-empress.png",
    toneGuide: "따뜻하고 풍요로운 에너지. 성장과 번영의 계절.",
    isActive: true,
  },
  "the-emperor": {
    id: "the-emperor",
    name: "The Emperor",
    nameKo: "황제",
    arcana: "major",
    number: 4,
    keywords: ["authority", "structure", "stability", "control"],
    keywordsKo: ["권위", "구조", "안정성", "통제"],
    meaningUpright: "강한 기반, 안정적 구조, 권위 있는 세력의 영향",
    meaningReversed: "경직성, 과도한 통제, 권력 남용",
    imageUrl: "/cards/the-emperor.png",
    toneGuide: "강하고 안정적인 에너지. 확고한 구조와 질서.",
    isActive: true,
  },
  "the-hierophant": {
    id: "the-hierophant",
    name: "The Hierophant",
    nameKo: "교황",
    arcana: "major",
    number: 5,
    keywords: ["tradition", "convention", "institution", "guidance"],
    keywordsKo: ["전통", "관례", "기관", "지침"],
    meaningUpright: "전통적 접근, 기관의 영향, 검증된 방법론",
    meaningReversed: "관습 타파, 비전통적 선택, 제도권 저항",
    imageUrl: "/cards/the-hierophant.png",
    toneGuide: "엄숙하고 권위 있는 에너지. 전통과 규범의 무게.",
    isActive: true,
  },
  "the-lovers": {
    id: "the-lovers",
    name: "The Lovers",
    nameKo: "연인",
    arcana: "major",
    number: 6,
    keywords: ["choice", "alignment", "partnership", "values"],
    keywordsKo: ["선택", "정렬", "파트너십", "가치관"],
    meaningUpright: "중요한 선택의 기로, 가치관 기반 결정",
    meaningReversed: "잘못된 선택, 불균형, 가치 충돌",
    imageUrl: "/cards/the-lovers.png",
    toneGuide: "달콤하면서도 무게감 있는 에너지. 중요한 갈림길.",
    isActive: true,
  },
  "the-chariot": {
    id: "the-chariot",
    name: "The Chariot",
    nameKo: "전차",
    arcana: "major",
    number: 7,
    keywords: ["determination", "momentum", "victory", "control"],
    keywordsKo: ["결단", "모멘텀", "승리", "통제"],
    meaningUpright: "강한 모멘텀, 의지로 이끄는 승리, 방향성 확립",
    meaningReversed: "방향 상실, 통제 불능, 충동적 행동",
    imageUrl: "/cards/the-chariot.png",
    toneGuide: "힘차고 전진하는 에너지. 강한 의지와 추진력.",
    isActive: true,
  },
  "strength": {
    id: "strength",
    name: "Strength",
    nameKo: "힘",
    arcana: "major",
    number: 8,
    keywords: ["courage", "patience", "inner strength", "resilience"],
    keywordsKo: ["용기", "인내", "내면의 힘", "회복력"],
    meaningUpright: "내면의 강인함, 인내심, 두려움을 극복하는 용기",
    meaningReversed: "자기 의심, 내면의 갈등, 힘의 남용",
    imageUrl: "/cards/strength.png",
    toneGuide: "조용하지만 강인한 에너지. 폭풍 속의 고요함.",
    isActive: true,
  },
  "the-hermit": {
    id: "the-hermit",
    name: "The Hermit",
    nameKo: "은둔자",
    arcana: "major",
    number: 9,
    keywords: ["introspection", "solitude", "guidance", "patience"],
    keywordsKo: ["성찰", "고독", "내면 탐구", "인내"],
    meaningUpright: "관망의 시기, 내면 성찰, 서두르지 않는 지혜",
    meaningReversed: "고립, 기회 회피, 과도한 내향성",
    imageUrl: "/cards/the-hermit.png",
    toneGuide: "조용하고 사색적인 에너지. 한 발 물러서는 지혜.",
    isActive: true,
  },
  "wheel-of-fortune": {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    nameKo: "운명의 수레바퀴",
    arcana: "major",
    number: 10,
    keywords: ["cycles", "turning point", "fate", "opportunity"],
    keywordsKo: ["사이클", "전환점", "운명", "기회"],
    meaningUpright: "전환점, 사이클의 변화, 흐름을 타는 기회",
    meaningReversed: "저항하는 변화, 나쁜 타이밍, 외부 요인의 방해",
    imageUrl: "/cards/wheel-of-fortune.png",
    toneGuide: "역동적이고 변화무쌍한 에너지. 수레바퀴가 도는 순간.",
    isActive: true,
  },
  "justice": {
    id: "justice",
    name: "Justice",
    nameKo: "정의",
    arcana: "major",
    number: 11,
    keywords: ["fairness", "cause and effect", "truth", "law"],
    keywordsKo: ["공정성", "인과응보", "진실", "법칙"],
    meaningUpright: "공정한 결과, 인과의 법칙, 냉정한 판단",
    meaningReversed: "불공정, 책임 회피, 편향된 판단",
    imageUrl: "/cards/justice.png",
    toneGuide: "냉정하고 균형 잡힌 에너지. 저울이 가리키는 진실.",
    isActive: true,
  },
  "the-hanged-man": {
    id: "the-hanged-man",
    name: "The Hanged Man",
    nameKo: "매달린 사람",
    arcana: "major",
    number: 12,
    keywords: ["pause", "perspective", "surrender", "waiting"],
    keywordsKo: ["정지", "관점 전환", "내려놓음", "기다림"],
    meaningUpright: "자발적 정지, 다른 각도의 통찰, 기다림의 가치",
    meaningReversed: "지연, 저항, 희생 거부",
    imageUrl: "/cards/the-hanged-man.png",
    toneGuide: "고요하고 묘한 에너지. 세상을 거꾸로 보는 시각.",
    isActive: true,
  },
  "death": {
    id: "death",
    name: "Death",
    nameKo: "죽음",
    arcana: "major",
    number: 13,
    keywords: ["transformation", "ending", "transition", "renewal"],
    keywordsKo: ["변환", "끝", "전환", "갱신"],
    meaningUpright: "한 시대의 끝, 변환과 재탄생, 낡은 것의 소멸",
    meaningReversed: "변화 저항, 정체, 완전한 마무리 실패",
    imageUrl: "/cards/death.png",
    toneGuide: "엄숙하면서도 해방적인 에너지. 끝이 곧 시작임을 아는 고요함.",
    isActive: true,
  },
  "temperance": {
    id: "temperance",
    name: "Temperance",
    nameKo: "절제",
    arcana: "major",
    number: 14,
    keywords: ["balance", "moderation", "patience", "harmony"],
    keywordsKo: ["균형", "절제", "인내", "조화"],
    meaningUpright: "균형과 조화, 장기적 관점, 서두르지 않는 접근",
    meaningReversed: "불균형, 과잉, 극단적 행동",
    imageUrl: "/cards/temperance.png",
    toneGuide: "차분하고 조화로운 에너지. 두 흐름이 만나 새로운 것을 만드는 순간.",
    isActive: true,
  },
  "the-devil": {
    id: "the-devil",
    name: "The Devil",
    nameKo: "악마",
    arcana: "major",
    number: 15,
    keywords: ["bondage", "materialism", "shadow", "temptation"],
    keywordsKo: ["속박", "물질주의", "그림자", "유혹"],
    meaningUpright: "탐욕과 집착, 단기 유혹, 보이지 않는 족쇄",
    meaningReversed: "속박으로부터의 해방, 패턴 인식, 의식적 선택",
    imageUrl: "/cards/the-devil.png",
    toneGuide: "무겁고 도발적인 에너지. 유혹의 본질을 직시하는 시간.",
    isActive: true,
  },
  "the-tower": {
    id: "the-tower",
    name: "The Tower",
    nameKo: "탑",
    arcana: "major",
    number: 16,
    keywords: ["sudden change", "disruption", "revelation", "chaos"],
    keywordsKo: ["급격한 변화", "붕괴", "폭로", "혼란"],
    meaningUpright: "급격한 붕괴와 재편, 예상치 못한 충격, 낡은 구조의 해체",
    meaningReversed: "재앙 회피, 변화 저항, 내부의 불안",
    imageUrl: "/cards/the-tower.png",
    toneGuide: "강렬하고 충격적인 에너지. 번개가 탑을 치는 순간.",
    isActive: true,
  },
  "the-star": {
    id: "the-star",
    name: "The Star",
    nameKo: "별",
    arcana: "major",
    number: 17,
    keywords: ["hope", "renewal", "inspiration", "serenity"],
    keywordsKo: ["희망", "회복", "영감", "고요함"],
    meaningUpright: "폭풍 후의 희망, 회복의 신호, 장기적 낙관",
    meaningReversed: "희망 상실, 실망, 불신",
    imageUrl: "/cards/the-star.png",
    toneGuide: "부드럽고 희망적인 에너지. 어둠 뒤에 빛나는 별.",
    isActive: true,
  },
  "the-moon": {
    id: "the-moon",
    name: "The Moon",
    nameKo: "달",
    arcana: "major",
    number: 18,
    keywords: ["illusion", "fear", "uncertainty", "subconscious"],
    keywordsKo: ["환상", "두려움", "불확실성", "무의식"],
    meaningUpright: "불확실성과 안개, 숨겨진 리스크, 감정적 판단 주의",
    meaningReversed: "혼란 해소, 진실 드러남, 두려움 극복",
    imageUrl: "/cards/the-moon.png",
    toneGuide: "몽환적이고 불안한 에너지. 달빛 아래 숨겨진 그림자.",
    isActive: true,
  },
  "the-sun": {
    id: "the-sun",
    name: "The Sun",
    nameKo: "태양",
    arcana: "major",
    number: 19,
    keywords: ["success", "clarity", "vitality", "positivity"],
    keywordsKo: ["성공", "명확성", "활력", "긍정"],
    meaningUpright: "밝은 전망, 명확한 방향성, 성공의 에너지",
    meaningReversed: "과도한 낙관, 일시적 흐림, 자만",
    imageUrl: "/cards/the-sun.png",
    toneGuide: "밝고 따뜻한 에너지. 모든 것이 선명하게 보이는 순간.",
    isActive: true,
  },
  "judgement": {
    id: "judgement",
    name: "Judgement",
    nameKo: "심판",
    arcana: "major",
    number: 20,
    keywords: ["reflection", "reckoning", "awakening", "renewal"],
    keywordsKo: ["반성", "심판", "각성", "갱신"],
    meaningUpright: "중요한 평가의 시점, 과거 패턴 청산, 새로운 소명",
    meaningReversed: "자기 비판 과잉, 과거에 얽매임, 판단 회피",
    imageUrl: "/cards/judgement.png",
    toneGuide: "엄숙하고 각성적인 에너지. 나팔 소리가 울리는 순간.",
    isActive: true,
  },
  "the-world": {
    id: "the-world",
    name: "The World",
    nameKo: "세계",
    arcana: "major",
    number: 21,
    keywords: ["completion", "integration", "accomplishment", "wholeness"],
    keywordsKo: ["완성", "통합", "성취", "전체성"],
    meaningUpright: "사이클의 완성, 목표 달성, 전체적 통합",
    meaningReversed: "미완성, 지연, 외부 승인에 대한 의존",
    imageUrl: "/cards/the-world.png",
    toneGuide: "충만하고 완성된 에너지. 여정의 완결과 새로운 시작의 경계.",
    isActive: true,
  },
};

export const ACTIVE_CARDS = Object.values(TAROT_CARDS).filter((c) => c.isActive);

export function getCardById(id: TarotCardId): TarotCardMeta {
  const card = TAROT_CARDS[id];
  return card;
}
